# Generated by Django 6.1.1 on 2026-10-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sintomas',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
